services:

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    shm_size: 256mb
    environment:
      POSTGRES_USER: mastodon
      POSTGRES_PASSWORD: mastodon
    volumes:
      - ${POSTGRES_SERVICE_VOLUME_PATH}Data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - ${REDIS_SERVICE_VOLUME_PATH}Data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  web:
    image: ghcr.io/mastodon/mastodon:${MASTODON_VERSION}
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    command: bundle exec puma -C config/puma.rb
    env_file: Environment/.${MASTODON_ENVIRONMENT_FILE}.env
    volumes:
      - ${MASTODON_SERVICE_VOLUME_PATH}Public/System:/mastodon/public/system
      - ${MASTODON_SERVICE_VOLUME_PATH}Other:/Other
      # - ${MASTODON_SERVICE_VOLUME_PATH}Other/logo-symbol-wordmark.svg:/mastodon/app/javascript/images/logo-symbol-wordmark.svg
    ports:
      - ${MASTODON_HTTP_IP}:${MASTODON_HTTP_PORT}:3000
    healthcheck:
      test: ['CMD-SHELL',"curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' || exit 1"]

  streaming:
    image: ghcr.io/mastodon/mastodon-streaming:${MASTODON_VERSION}
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    command: node ./streaming/index.js
    env_file: Environment/.${MASTODON_ENVIRONMENT_FILE}.env
    ports:
      - ${MASTODON_STREAMING_HTTP_IP}:${MASTODON_STREAMING_HTTP_PORT}:4000
    healthcheck:
      test: ['CMD-SHELL', "curl -s --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1"]

  sidekiq:
    image: ghcr.io/mastodon/mastodon:${MASTODON_VERSION}
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    command: bundle exec sidekiq
    env_file: Environment/.${MASTODON_ENVIRONMENT_FILE}.env
    volumes:
      - ${MASTODON_SERVICE_VOLUME_PATH}Public/System:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ [78]' || false"]

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK_SUBNET}